const fs = require('fs');
const path = require('path');

const packageJsonPath = path.join(__dirname, '..', 'package.json');
const versionJsPath = path.join(__dirname, '..', 'Version.js');

const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
const version = packageJson.version;

const versionJsContent = `// This file is automatically generated. Do not edit manually.
var APP_VERSION = '${version}';
console.log('App version: ' + APP_VERSION);
`;

fs.writeFileSync(versionJsPath, versionJsContent);
console.log(`Updated Version.js to version ${version}`);
